version: "3.9"
networks:
  web:
    external: true
    
services:    
  app:
    image: $IMAGE:$CI_COMMIT_SHORT_SHA
    container_name: ${CONTAINER_NAME}-storybook
    restart: always
    tty: true
    networks:
      - web
    ports:
      - 3001:3000