version: "3.9"
networks:
  web:
    external: true

services:
  app:
    image: $IMAGE:$CI_COMMIT_SHORT_SHA
    container_name: ${CONTAINER_NAME}-frontend
    restart: always
    tty: true
    networks:
      - web
    ports:
      - 3000:3000
